version: '3.7'


services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn personal_website.wsgi:application --bind 0.0.0.0:8000 --timeout 120
    volumes:
      - static_volume:/var/www/personal_website/static
      - media_volume:/var/www/personal_website/media
    env_file:
      - ./.env.prod
    expose:
      - 8000
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/var/www/personal_website/static
      - media_volume:/var/www/personal_website/media
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
