version: '3.7'


services:
  web:
    build: .
    command: gunicorn personal_website.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env.prod
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data:
